[workspace.package]
authors = ["Ziwei Wu <w_ziwei2004@163.com>"]
edition = "2024"
license = "MIT"
repository = "https://github.com/iAeternus/mylib.git"
homepage = "https://github.com/iAeternus"

[workspace]
members = ["mylib","num"]
resolver = "3"
